services:
  webapp:
    build:
      context: .
      args:
        - DOCKER_BUILDKIT=1 
    ports:
      - 3000:3000

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc123
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: abc123
      ME_CONFIG_MONGODB_URL: mongodb://root:abc123@mongo:27017/

volumes:
  mongodb: